export MILL_LIB=../../builds/scratchip/jars
export COURSIER_CACHE=../../builds/scratchip/.cache

base_dir=../..
verilog:
	chmod +x ../../builds/scratchip/mill
	../../builds/scratchip/mill chisel.run -td $(base_dir)/builds
